"""Generated by tools/vendor.py — what this family was cut from.

Hand-edited after vendoring (knobs frozen, dead branches removed, call cache
unified), so these hashes identify the SOURCE, not the files here. drift.py
compares them against the ladder's current HEAD.
"""

SOURCE_COMMIT = "6fc6309"
SOURCE_FILES = {
    "kernels/cconv/ideas/001-strip-onepass/kernel.py": "b8c2d3a246466fc21ddeb66cebac50df3073855649aebd6fd67e241561efc4da",
}
