"""Dump a RULER difficulty ladder (increasing context size) to a txt file.

For each subtask and each rung (num_docs), generate one example, render the full
training prompt + expected output via build_prompt, and write a readable block.
"""
import json
import os
import subprocess
import sys
import tempfile
 # sys.path hack removed: corpus_reasoning is a package on PYTHONPATH=src
from corpus_reasoning.lib.data_format import build_prompt

SUBTASKS = ["niah_single", "niah_multikey", "niah_multivalue",
            "niah_multiquery", "vt", "cwe", "fwe"]
RUNGS = [10, 30, 60]  # num_docs ladder
OUT = "examples/ruler_ladder.txt"

os.makedirs("examples", exist_ok=True)
tmp = tempfile.mkdtemp()
lines = []


def hr(c="="):
    return c * 80


lines.append(hr())
lines.append("RULER in-domain task ladder — sample TRAIN examples")
lines.append("Generated by scripts/data/generate_ruler_data.py (num_docs mode)")
lines.append("Each block shows the full rendered prompt + the expected output target.")
lines.append(hr())

for sub in SUBTASKS:
    for n in RUNGS:
        subprocess.run([
            sys.executable, "scripts/data/generate_ruler_data.py",
            "--subtask", sub, "--length-mode", "num_docs", "--num-docs", str(n),
            "--num-train", "1", "--num-eval", "1", "--disjoint-vocab",
            "--output-dir", tmp, "--seed", "7",
        ], check=True, stdout=subprocess.DEVNULL)
        train = [f for f in os.listdir(tmp)
                 if f.startswith(f"ruler_{sub}_") and f.endswith("_train.jsonl")][0]
        ex = json.loads(open(os.path.join(tmp, train)).readline())
        os.remove(os.path.join(tmp, train))  # avoid stale-file collisions
        prompt, output = build_prompt(ex, task="ruler", use_alpaca=True)
        lines.append("")
        lines.append(hr())
        lines.append(f"SUBTASK: {sub}   |   rung: num_docs={n}   |   "
                     f"actual docs={len(ex['documents'])}   |   "
                     f"gold answers={len(ex['answers'])}")
        lines.append(f"answers (recall target): {ex['answers']}")
        lines.append(f"gold_doc_indices (needle positions): {ex['gold_doc_indices']}")
        lines.append(hr("-"))
        lines.append("[PROMPT]")
        lines.append(prompt)
        lines.append("[EXPECTED OUTPUT]")
        lines.append(output)

open(OUT, "w").write("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(lines)} lines)")
