"""Publish compact, read-only diagnostics from our completed trusted profile artifacts."""

import argparse
import gzip
import json
import os
import pickle
import shutil
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path("/weka/olmo-3p5-checkpoints/production-profiling")


def main():
    """Read saved traces; do not run training or mutate any source artifacts."""
    parser = argparse.ArgumentParser()
    parser.add_argument("run_name")
    args = parser.parse_args()
    if Path(args.run_name).name != args.run_name:
        raise ValueError("Expected a run directory name")
    source = ROOT / args.run_name
    output = Path(os.environ.get("RESULTS_DIR", "/results")) / "diagnostics" / args.run_name
    output.mkdir(parents=True, exist_ok=True)
    for name in ("analysis.json", "metrics.jsonl", "provenance.json"):
        shutil.copy2(source / name, output / name)
    distributed = []
    for path in sorted((source / "profiler").glob("*.distributed-events.json")):
        shutil.copy2(path, output / path.name)
        distributed.append(json.loads(path.read_text()))

    analysis = json.loads((source / "analysis.json").read_text())
    for trace in analysis.get("traces", []):
        brief = {
            key: value
            for key, value in trace.items()
            if isinstance(value, (int, float)) or key == "trace"
        }
        print("TRACE_UNIONS", json.dumps(brief), flush=True)
        if "rank-0-" in trace["trace"]:
            for op in trace.get("gpu_kernel_time_by_originating_cpu_op_nonadditive", [])[:25]:
                print("GPU_ORIGIN", json.dumps(op), flush=True)

    trace_path = next((source / "profiler").glob("rank-0-*.chrome_trace.json.gz"))
    with gzip.open(trace_path, "rt") as handle:
        trace = json.load(handle)
    # Recover actual op shapes/dtypes/strides when Kineto recorded them. Kernel names
    # alone cannot tell us whether a gradient input is contiguous or mixed precision.
    hot_ops = {}
    for event in trace["traceEvents"]:
        if event.get("cat") != "cpu_op" or event.get("name") not in (
            "aten::mm",
            "aten::_grouped_mm",
            "aten::add_",
            "aten::copy_",
        ):
            continue
        metadata = {
            key: value for key, value in event.get("args", {}).items() if key.startswith("Input ")
        }
        key = json.dumps({"name": event["name"], **metadata}, sort_keys=True)
        entry = hot_ops.setdefault(
            key, {"count": 0, "cpu_duration_us": 0.0, "gpu_duration_us_sum": 0.0}
        )
        entry["count"] += 1
        entry["cpu_duration_us"] += event.get("dur", 0)
    by_external = {
        e["args"]["External id"]: e
        for e in trace["traceEvents"]
        if e.get("cat") == "cpu_op" and e.get("args", {}).get("External id")
    }
    for event in trace["traceEvents"]:
        if event.get("cat") != "kernel":
            continue
        origin = by_external.get(event.get("args", {}).get("External id"))
        if origin is not None and origin["name"] in (
            "aten::mm",
            "aten::_grouped_mm",
            "aten::add_",
            "aten::copy_",
        ):
            metadata = {
                key: value
                for key, value in origin.get("args", {}).items()
                if key.startswith("Input ")
            }
            key = json.dumps({"name": origin["name"], **metadata}, sort_keys=True)
            hot_ops[key]["gpu_duration_us_sum"] += event.get("dur", 0)
    hot_ops = [{"metadata": json.loads(key), **value} for key, value in hot_ops.items()]
    hot_ops.sort(key=lambda entry: -entry["gpu_duration_us_sum"])
    (output / "hot-op-shapes.json").write_text(json.dumps(hot_ops, indent=2))
    for entry in hot_ops[:20]:
        print("HOT_OP_SHAPE", json.dumps(entry), flush=True)
    communication = defaultdict(lambda: {"count": 0, "cpu_duration_us": 0.0})
    for event in trace["traceEvents"]:
        if event.get("name") != "record_param_comms":
            continue
        # Keep actual profiler payload keys rather than inferring bytes from kernel names.
        fields = {
            key: value
            for key, value in event.get("args", {}).items()
            if key not in ("External id", "Record function id", "Sequence number", "Ev Idx")
            and "sequence" not in key.lower()
        }
        entry = communication[json.dumps(fields, sort_keys=True)]
        entry["count"] += 1
        entry["cpu_duration_us"] += event.get("dur", 0)
    communication = [{"metadata": json.loads(key), **value} for key, value in communication.items()]
    (output / "communication-payloads.json").write_text(json.dumps(communication, indent=2))
    print("COMMUNICATION_METADATA_GROUPS", len(communication), flush=True)
    for entry in sorted(communication, key=lambda x: -x["cpu_duration_us"])[:15]:
        print("COMMUNICATION_METADATA", json.dumps(entry), flush=True)

    # This is a pickle generated by this branch's own training callback, not user input.
    # Keep raw snapshots on Weka and publish only schema/accounting/allocation-site summaries.
    with (source / "memory" / "memsnapshot.0.pickle").open("rb") as handle:
        snapshot = pickle.load(handle)
    history = snapshot.get("device_traces", [])
    allocations = defaultdict(lambda: {"count": 0, "allocated_bytes_sum": 0})
    actions = Counter()
    for device_history in history:
        for event in device_history:
            actions[event["action"]] += 1
            if event["action"] != "alloc":
                continue
            frames = event.get("frames", [])
            python_frames = [f for f in frames if str(f.get("filename", "")).endswith(".py")]
            key = json.dumps(python_frames[:8] or frames[:3], sort_keys=True)
            allocations[key]["count"] += 1
            allocations[key]["allocated_bytes_sum"] += event.get("size", 0)
    memory = {
        "snapshot_keys": sorted(snapshot),
        "device_history_lengths": [len(x) for x in history],
        "history_action_counts": dict(actions),
        "segments": len(snapshot.get("segments", [])),
        "snapshot_segment_bytes": sum(s["total_size"] for s in snapshot.get("segments", [])),
        "snapshot_active_bytes": sum(s["active_size"] for s in snapshot.get("segments", [])),
        "snapshot_allocated_bytes": sum(s["allocated_size"] for s in snapshot.get("segments", [])),
        "largest_allocation_sites_by_cumulative_bytes": [
            {"frames": json.loads(key), **value}
            for key, value in sorted(
                allocations.items(), key=lambda x: -x[1]["allocated_bytes_sum"]
            )[:30]
        ],
        "caveat": (
            "Cumulative allocation traffic is not live memory or a peak. The bounded "
            "history may omit older events; use trainer per-step metrics for activation peaks."
        ),
    }
    (output / "memory-diagnostics.json").write_text(json.dumps(memory, indent=2))
    print(
        "MEMORY_ACCOUNTING",
        json.dumps(
            {k: v for k, v in memory.items() if k != "largest_allocation_sites_by_cumulative_bytes"}
        ),
        flush=True,
    )
    print(f"Saved compact diagnostics to {output}", flush=True)


if __name__ == "__main__":
    main()
