#!/usr/bin/env python
"""Compose the length-mix experiment's per-arm shard dirs from two shared pools.

Design: every arm gets an IDENTICAL long pool and a growing amount of short data on top. Arms are
built as directories of SYMLINKS into the two pools, so the token data is stored once no matter how
many arms reference it (10 arms x copied data would be ~3 GB of pointless duplication, and on weka
that is also 10x the sync time).

Part files are whole-example granular (the converter flushes on a token budget, but only after a
complete example), so selecting a subset of parts selects a subset of examples -- no re-tokenizing.

`metadata.json` is regenerated per arm because the trainers HARD-require it: `num_instances` drives
the mask-mix anneal and `max_example_len` guards `--seq-len`. num_instances is recovered by counting
EOS ids (every example is EOS-terminated by the converter).

Run this where the pools are fast to read (weka), not over /scratch NFS.
"""
import argparse
import json
import os

import numpy as np

# S/L ratios in TOKENS. Row A = full long pool, Row B = half long pool (gives the
# substitute-vs-complement interaction).
ARMS = [
    ("A0", 1.0, 0.0),
    ("A1", 1.0, 0.5),
    ("A2", 1.0, 1.0),
    ("A3", 1.0, 2.0),
    ("A4", 1.0, 4.0),
    ("B0", 0.5, 0.0),
    ("B2", 0.5, 1.0),
    ("B4", 0.5, 4.0),
]

# Row C: the iso-token reference. Same UNIFORM 2k-32k composition the production mix uses, drawn
# from a pool generated by the same generator/fillers/tokenizer run as rows A/B -- so C differs
# from A only in length COMPOSITION, never in provenance. Each C arm is capped to the exact total
# token budget of the A arm it mirrors, which is what makes "does piling on short data beat the
# production mix at equal cost?" a fair question.
C_MIRRORS = [("C3", "A3"), ("C4", "A4")]


def part_stats(pool, eos_id):
    """Per-part (tokens, instances) for a pool dir, in part order."""
    parts = sorted(f for f in os.listdir(pool) if f.startswith("token_ids_part_"))
    out = []
    for f in parts:
        ids = np.fromfile(os.path.join(pool, f), dtype=np.uint32)
        out.append((f, len(ids), int((ids == eos_id).sum())))
    return out


def take_until(stats, target_tokens):
    """Greedily take whole parts until target_tokens is reached (never exceeds by a whole part)."""
    sel, tok, inst = [], 0, 0
    for f, t, n in stats:
        if target_tokens <= 0 or tok >= target_tokens:
            break
        sel.append(f)
        tok += t
        inst += n
    return sel, tok, inst


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pool-long", required=True)
    ap.add_argument("--pool-short", required=True)
    ap.add_argument("--pool-uniform", default=None, help="Row C reference pool (uniform 2k-32k)")
    ap.add_argument("--out-root", required=True)
    ap.add_argument("--eos-id", type=int, default=248044, help="qwen3_5 eos")
    args = ap.parse_args()

    meta_long = json.load(open(os.path.join(args.pool_long, "metadata.json")))
    meta_short = json.load(open(os.path.join(args.pool_short, "metadata.json")))
    sl = part_stats(args.pool_long, args.eos_id)
    ss = part_stats(args.pool_short, args.eos_id)
    L_tok = sum(t for _, t, _ in sl)
    S_tok = sum(t for _, t, _ in ss)
    print(f"pool_long : {len(sl)} parts, {L_tok/1e6:.1f}M tok")
    print(f"pool_short: {len(ss)} parts, {S_tok/1e6:.1f}M tok")

    rows = []
    totals = {}
    for name, lfrac, sratio in ARMS:
        long_target = L_tok * lfrac
        lsel, ltok, linst = take_until(sl, long_target)
        # S/L is relative to THIS arm's long budget, so B-row ratios stay comparable to A-row.
        short_target = ltok * sratio
        ssel, stok, sinst = take_until(ss, short_target)
        if sratio > 0 and stok < short_target * 0.95:
            raise SystemExit(
                f"FATAL {name}: short pool exhausted ({stok/1e6:.1f}M < {short_target/1e6:.1f}M "
                "requested). Arms would silently repeat data -> epoch-count confound. Generate "
                "more short examples before running."
            )
        d = os.path.join(args.out_root, name)
        os.makedirs(d, exist_ok=True)
        idx = 0
        for pool, sel in ((args.pool_long, lsel), (args.pool_short, ssel)):
            for f in sel:
                for kind in ("token_ids", "labels_mask"):
                    src = os.path.join(pool, f.replace("token_ids", kind))
                    dst = os.path.join(d, f"{kind}_part_{idx:06d}.npy")
                    if not os.path.exists(dst):
                        os.symlink(src, dst)
                idx += 1
        meta = dict(meta_long)
        meta.update(
            num_instances=linst + sinst,
            num_tokens=ltok + stok,
            max_example_len=max(meta_long["max_example_len"], meta_short["max_example_len"]),
            min_example_len=min(meta_long["min_example_len"], meta_short["min_example_len"]),
            num_dropped=0,
            length_mix={
                "arm": name, "long_frac": lfrac, "short_over_long": sratio,
                "long_tokens": ltok, "short_tokens": stok,
                "long_instances": linst, "short_instances": sinst,
                # the anti-confound receipt: <=1.0 means no arm repeats short data
                "short_pool_fraction_used": (stok / S_tok) if S_tok else 0.0,
            },
        )
        json.dump(meta, open(os.path.join(d, "metadata.json"), "w"), indent=1)
        rows.append((name, ltok, stok, linst, sinst, stok / S_tok if S_tok else 0))
        totals[name] = ltok + stok
        print(f"  {name}: long {ltok/1e6:6.1f}M ({linst:5d} ex) + short {stok/1e6:6.1f}M "
              f"({sinst:6d} ex) = {(ltok+stok)/1e6:6.1f}M tok  [short pool used "
              f"{100*stok/S_tok if S_tok else 0:.0f}%]")

    # ---- Row C: uniform-composition reference at the SAME total token budget ----
    if args.pool_uniform:
        meta_u = json.load(open(os.path.join(args.pool_uniform, "metadata.json")))
        su = part_stats(args.pool_uniform, args.eos_id)
        U_tok = sum(t for _, t, _ in su)
        print(f"pool_uniform: {len(su)} parts, {U_tok/1e6:.1f}M tok")
        for cname, mirror in C_MIRRORS:
            target = totals[mirror]
            usel, utok, uinst = take_until(su, target)
            if utok < target * 0.95:
                raise SystemExit(
                    f"FATAL {cname}: uniform pool too small ({utok/1e6:.1f}M < {target/1e6:.1f}M "
                    f"needed to match {mirror}). Row C would not be iso-token -> the "
                    "'cheaper at equal cost?' comparison would be invalid."
                )
            d = os.path.join(args.out_root, cname)
            os.makedirs(d, exist_ok=True)
            for i, f in enumerate(usel):
                for kind in ("token_ids", "labels_mask"):
                    src = os.path.join(args.pool_uniform, f.replace("token_ids", kind))
                    dst = os.path.join(d, f"{kind}_part_{i:06d}.npy")
                    if not os.path.exists(dst):
                        os.symlink(src, dst)
            meta = dict(meta_u)
            meta.update(
                num_instances=uinst, num_tokens=utok, num_dropped=0,
                length_mix={"arm": cname, "composition": "uniform_2k_32k",
                            "mirrors": mirror, "target_tokens": target},
            )
            json.dump(meta, open(os.path.join(d, "metadata.json"), "w"), indent=1)
            print(f"  {cname}: uniform {utok/1e6:6.1f}M ({uinst:5d} ex) "
                  f"[mirrors {mirror} @ {target/1e6:.1f}M, delta {100*(utok-target)/target:+.1f}%]")

    print("\nAll arms composed. Every arm draws short data WITHOUT repetition "
          "(short_pool_fraction_used <= 1.0).")


if __name__ == "__main__":
    main()
