name: Python virtualenv
description: Set up a Python virtual environment with uv
inputs:
  python-version:
    description: The Python version to use
    required: true
  cache-prefix:
    description: Update this to invalidate the cache
    required: true
    default: v0
  torch-version:
    description: The PyTorch version to install
    required: false
    default: '2.7.0'
  torchao-version:
    description: The torchao version to install
    required: false
    default: '0.9.0'
  channel:
    description: The channel to install from
    required: false
    default: 'whl/cpu'

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-uv-${{ inputs.python-version }}-${{ inputs.torch-version }}-${{ inputs.torchao-version }}-${{ hashFiles('uv.lock') }}

    - name: Create torch override
      shell: bash
      run: |
        echo "torch==${{ inputs.torch-version }}" > /tmp/torch-override.txt
        echo "torchao==${{ inputs.torchao-version }}" >> /tmp/torch-override.txt

    - name: Install dependencies
      shell: bash
      env:
        UV_EXTRA_INDEX_URL: https://download.pytorch.org/${{ inputs.channel }}
        UV_OVERRIDE: /tmp/torch-override.txt
      run: uv sync --frozen --extra dev

    - name: Show environment info
      shell: bash
      run: |
        echo "Installed $(uv run python --version)"
        uv run pip list
