name: Python virtualenv
description: Set up a Python virtual environment with uv
inputs:
  python-version:
    description: The Python version to use
    required: true
  cache-prefix:
    description: Update this to invalidate the cache
    required: true
    default: v0

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-uv-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen --extra dev

    - name: Show environment info
      shell: bash
      run: |
        echo "Installed $(uv run python --version)"
        uv run pip list
