"""Generate MS MARCO passage re-ranking data (the `rerank` task).

Each dev query → one example: a candidate pool of passages (the gold + BM25
distractors), shuffled, which the model must rank by relevance. Scored by MRR@10
(`--task rerank`). Also serves the suite's "full passage re-ranking" row (raise
--num-docs to rank a larger pool).

Uses pyserini's prebuilt `msmarco-v1-passage` Lucene index for BOTH BM25 search
and passage text (no 8.8M-passage download needed). Queries + qrels come from
BeIR/msmarco (dev split); MS MARCO pids align with the pyserini docids.

Needs pyserini + HF datasets → run via sbatch (jobs/gen_msmarco.sh).

Usage:
    python scripts/data/generate_msmarco_data.py --num-docs 50 \\
        --num-queries 1000 --output-dir data
"""

import argparse
import json
import random
from collections import defaultdict


def _passage_text(searcher, pid):
    doc = searcher.doc(pid)
    if doc is None:
        return None
    raw = doc.raw()
    try:
        obj = json.loads(raw)
        return obj.get("contents") or obj.get("text") or raw
    except (json.JSONDecodeError, TypeError):
        return raw


def main():
    raise NotImplementedError(
        "DEPRECATED: generate_msmarco_data.py produces the OLD binary rerank format "
        "(gold-first reference order, no per-doc `ce_scores`). It is disabled so the "
        "stale format can't be regenerated by accident. Use "
        "generate_msmarco_trainhn_data.py (CE-graded: emits `ce_scores` for graded "
        "relevance order + NDCG@10/Kendall-tau eval). To intentionally run the old "
        "path, remove this guard."
    )
    from pyserini.search.lucene import LuceneSearcher
    from datasets import load_dataset

    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--index", default="msmarco-v1-passage")
    ap.add_argument("--split", default="dev")
    ap.add_argument("--num-docs", type=int, default=50,
                    help="candidates per example (gold + BM25 distractors)")
    ap.add_argument("--min-docs", type=int, default=None,
                    help="if set with --max-docs, sample candidates per example "
                         "uniformly in [min-docs, max-docs] (continuous "
                         "context-length sampling); overrides --num-docs")
    ap.add_argument("--max-docs", type=int, default=None,
                    help="upper bound (inclusive) for per-example candidate count")
    ap.add_argument("--num-queries", type=int, default=1000,
                    help="queries to sample (per shard when --num-shards > 1)")
    ap.add_argument("--num-shards", type=int, default=1,
                    help="partition the (seeded, shuffled) query pool into this "
                         "many disjoint shards for parallel generation")
    ap.add_argument("--shard-index", type=int, default=0,
                    help="which shard [0, num-shards) this process handles")
    ap.add_argument("--output-dir", default="data")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    range_mode = args.min_docs is not None and args.max_docs is not None
    if (args.min_docs is None) != (args.max_docs is None):
        ap.error("--min-docs and --max-docs must be set together")
    if range_mode and args.min_docs > args.max_docs:
        ap.error("--min-docs must be <= --max-docs")

    rng = random.Random(args.seed)
    print(f"Loading prebuilt index {args.index} ...")
    searcher = LuceneSearcher.from_prebuilt_index(args.index)

    queries_ds = load_dataset("BeIR/msmarco", "queries")["queries"]
    qrels_ds = load_dataset("BeIR/msmarco-qrels")
    qsplit = args.split if args.split in qrels_ds else list(qrels_ds.keys())[0]
    qrels = defaultdict(list)
    for r in qrels_ds[qsplit]:
        if int(r["score"]) > 0:
            qrels[str(r["query-id"])].append(str(r["corpus-id"]))
    qtext = {str(r["_id"]): r["text"] for r in queries_ds if str(r["_id"]) in qrels}
    print(f"  dev queries with qrels: {len(qrels)}  (text for {len(qtext)})")

    qids = [q for q in qrels if q in qtext]
    rng.shuffle(qids)
    if args.num_shards > 1:
        # Stride partition of the identically-shuffled pool => disjoint shards.
        qids = qids[args.shard_index :: args.num_shards]
    qids = qids[: args.num_queries]

    examples, skipped = [], 0
    for qid in qids:
        # Per-example candidate count = the context-length knob. In range mode
        # sample it uniformly so a single run spans many context lengths.
        nd = rng.randint(args.min_docs, args.max_docs) if range_mode else args.num_docs
        search_k = max(nd * 3, nd + 100)
        gold_pids = qrels[qid]
        hits = searcher.search(qtext[qid], k=search_k)
        gold_set = set(gold_pids)
        distractor_pids = [h.docid for h in hits if h.docid not in gold_set]
        need = nd - len(gold_pids)
        if need < 0:
            gold_pids, need = gold_pids[:nd], 0
        pool_pids = gold_pids + distractor_pids[:need]
        if len(pool_pids) < nd:
            skipped += 1
            continue
        texts = [(pid, _passage_text(searcher, pid)) for pid in pool_pids]
        texts = [(pid, t) for pid, t in texts if t]
        if len(texts) < nd:
            skipped += 1
            continue
        rng.shuffle(texts)
        gold_idx = [i for i, (pid, _) in enumerate(texts) if pid in gold_set]
        examples.append({
            "documents": [{"title": None, "text": t} for _, t in texts],
            "queries": [qtext[qid]],
            "answers": [""],
            "gold_doc_indices": gold_idx,
            "source": "msmarco",
            "num_docs": len(texts),
        })

    ktag = f"k{args.min_docs}-{args.max_docs}" if range_mode else f"k{args.num_docs}"
    stag = f"_s{args.shard_index}of{args.num_shards}" if args.num_shards > 1 else ""
    path = (f"{args.output_dir}/msmarco_{args.split}_rerank"
            f"_{ktag}{stag}_{len(examples)}.jsonl")
    with open(path, "w") as f:
        for ex in examples:
            f.write(json.dumps(ex) + "\n")
    print(f"{len(examples)} examples (skipped {skipped}) -> {path}")


if __name__ == "__main__":
    main()
