#!/usr/bin/env python
"""Build finite native-text replay manifests for the s002 vision-alignment run.

This is an offline catalog-to-manifest operation. It only reads already-materialized,
headerless ``uint32`` token files; it never downloads data or launches a job. Source IDs,
labels, remote paths, token counts, and byte digests are not accepted from the materialization
catalog. They are derived from the pinned s002 expanded path manifest, the pinned
``OLMo-mix-0925`` manifest, and a separately reviewed, code-pinned upstream provenance
artifact. The catalog only maps a parent path index to a local materialization.

Windows preserve the parent dataset's exact fixed-length grid: a sequence of length ``L``
reads ``L`` raw IDs, shifts labels within the instance, and ignores the final target. It
therefore contributes ``L - 1`` nominal loss-bearing positions before the parent's repetition
filter is applied.

The source catalog is strict JSON with this shape::

    {
      "format": "olmo_native_text_replay_source_catalog",
      "version": 2,
      "sources": [
        {
          "parent_path_index": 0,
          "path": "tokens/parent-000000.npy"
        }
      ]
    }

The mandatory upstream provenance artifact is not generated by this script. Its reviewed
path and SHA-256 must be set in ``S002_UPSTREAM_PROVENANCE_FILE`` and
``S002_UPSTREAM_PROVENANCE_SHA256``. It binds each parent index and path to its authoritative
token count and full-file SHA-256. Its strict shape is::

    {
      "format": "olmo_native_text_replay_upstream_provenance",
      "version": 1,
      "hash_algorithm": "sha256",
      "parent_paths_sha256": "<pinned expanded-path digest>",
      "parent_mix_sha256": "<pinned labelled-mix digest>",
      "sources": [
        {
          "parent_path_index": 0,
          "parent_path": "s3://ai2-llm/.../000000.npy",
          "num_tokens": 123456789,
          "sha256": "<authoritative full-object digest>"
        }
      ]
    }

The byte inventory must be produced or attested by the upstream data owner, independently of
the local replay materialization. This script fails closed when either code pin is absent.

Catalog paths are local and resolve relative to the catalog. Source proportions are derived
from exact usable window capacity. Repeated ``--*-min-source-tokens SOURCE=TOKENS`` flags
reserve minimum quotas for source labels from the pinned parent mix before the remainder is
apportioned. A normal build streams every source once and emits a pinned verification receipt
beside the manifests; training validates that receipt instead of repeatedly hashing the full
materialized corpus. Receipt version 2 also records the exact bytes of this named builder
implementation, both pinned parent-manifest digests, and the upstream provenance digest. The
builder digest is computed from ``__file__`` when Python loads the module, not embedded as a
fixed value in that same file, so it is reproducible without a self-referential hash.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, Mapping, Optional, Sequence, Tuple

if TYPE_CHECKING:
    from olmo_core.data.multimodal.native_text_replay import NativeTextReplayManifest

NATIVE_TEXT_REPLAY_FORMAT = "olmo_native_text_replay"
NATIVE_TEXT_REPLAY_VERSION = 2
SOURCE_CATALOG_FORMAT = "olmo_native_text_replay_source_catalog"
SOURCE_CATALOG_VERSION = 2
UPSTREAM_PROVENANCE_FORMAT = "olmo_native_text_replay_upstream_provenance"
UPSTREAM_PROVENANCE_VERSION = 1
VERIFICATION_RECEIPT_FORMAT = "olmo_native_text_replay_verification_receipt"
VERIFICATION_RECEIPT_VERSION = 2
VERIFICATION_RECEIPT_FILENAME = "native-text-replay-verification.json"
BUILDER_IMPLEMENTATION_REFERENCE = "src/scripts/data/build_s002_replay_manifest.py"
# This digest is intentionally computed from the module bytes Python loaded, rather than
# hard-coded into those same bytes. The receipt can therefore bind the exact implementation
# without creating an impossible self-referential hash. Reviewers pin the resulting receipt
# bytes and can recover the named implementation from the corresponding repository revision.
BUILDER_IMPLEMENTATION_SHA256 = hashlib.sha256(Path(__file__).resolve().read_bytes()).hexdigest()
S002_PARENT_CHECKPOINT = "/weka/oe-training-default/robertb/s002-step125500"
S002_PARENT_PATHS_FILE = f"{S002_PARENT_CHECKPOINT}/data_paths.txt"
S002_PARENT_MIX = "OLMo-mix-0925"
S002_PARENT_PATHS_SHA256 = "f1155957f4f249fc17e1c7067512e7d881ce6675c6b854d5ce089c649cec1c2d"
S002_PARENT_MIX_FILE = str(
    Path(__file__).resolve().parents[2] / "olmo_core" / "data" / "mixes" / "OLMo-mix-0925.txt"
)
S002_PARENT_MIX_SHA256 = "fcc6a82b9a5e868885decfbc30486967644c7ca482a7d687102f7ff597dbd7c9"
# No authoritative per-object byte inventory is present in the s002 checkpoint or repository.
# Production must remain closed until data owners publish one, review it independently, and pin
# its immutable path and digest here. Tests replace both constants with synthetic fixtures.
S002_UPSTREAM_PROVENANCE_FILE: Optional[str] = None
S002_UPSTREAM_PROVENANCE_SHA256: Optional[str] = None
S002_TOKENIZER = {
    "identifier": "allenai/dolma2-tokenizer",
    "vocab_size": 100_278,
    "eos_token_id": 100_257,
    "pad_token_id": 100_277,
}
S002_INSTANCE_FILTER = {
    "repetition_min_period": 1,
    "repetition_max_period": 13,
    "repetition_max_count": 32,
}
TOKEN_DTYPE = "uint32"
TOKEN_ITEM_SIZE = 4
SELECTION_ALGORITHM = "affine-grid-v1"
_SHA256_RE = re.compile(r"[0-9a-f]{64}")
_ROOT_FIELDS = frozenset({"format", "version", "sources"})
_SOURCE_FIELDS = frozenset({"parent_path_index", "path"})
_UPSTREAM_ROOT_FIELDS = frozenset(
    {
        "format",
        "version",
        "hash_algorithm",
        "parent_paths_sha256",
        "parent_mix_sha256",
        "sources",
    }
)
_UPSTREAM_SOURCE_FIELDS = frozenset({"parent_path_index", "parent_path", "num_tokens", "sha256"})


@dataclass(frozen=True)
class CatalogSource:
    """One validated, materialized token file from a source catalog.

    :param source_id: Stable file-level identifier.
    :param source_name: Parent-mixture source label used for allocation quotas.
    :param catalog_path: Path exactly as written in the source catalog.
    :param resolved_path: Absolute local path used for verification and replay reads.
    :param num_tokens: Number of headerless ``uint32`` tokens in the file.
    :param sha256: Authoritative and, by default, verified file digest.
    """

    source_id: str
    source_name: str
    parent_path_index: int
    parent_path: str
    catalog_path: str
    resolved_path: Path
    num_tokens: int
    sha256: str

    @property
    def size_bytes(self) -> int:
        """Return the exact expected byte size of the raw token file."""
        return self.num_tokens * TOKEN_ITEM_SIZE


@dataclass(frozen=True)
class SourceCatalog:
    """Validated source catalog plus stable raw and semantic fingerprints.

    :param path: Absolute path to the catalog JSON.
    :param sources: Sources sorted by stable file identifier.
    :param catalog_sha256: SHA-256 of the catalog bytes.
    :param parent_paths_sha256: Digest of the exact expanded s002 parent path manifest.
    :param parent_mix_sha256: Digest of the exact source-labelled parent mix manifest.
    :param upstream_provenance_sha256: Digest of the code-pinned authoritative byte inventory.
    :param materialized_sources_sha256: Canonical digest of local materialized source metadata.
    :param source_hashes_verified: Whether this process streamed and verified every source.
    """

    path: Path
    sources: Tuple[CatalogSource, ...]
    catalog_sha256: str
    parent_paths_sha256: str
    parent_paths_file: Path
    parent_mix_sha256: str
    parent_mix_file: Path
    upstream_provenance_sha256: str
    upstream_provenance_file: Path
    materialized_sources_sha256: str
    source_hashes_verified: bool


@dataclass(frozen=True)
class ReplayManifestPair:
    """In-memory train and holdout native replay manifests.

    :param train: Train manifest dictionary accepted by
        :class:`~olmo_core.data.multimodal.native_text_replay.NativeTextReplayManifest`.
    :param holdout: Disjoint holdout manifest dictionary using the same schema.
    :param manifest_dir: Directory against which both manifests' token paths are relative.
    :param verification_receipt: Immutable offline integrity receipt, or ``None`` when the
        explicit development-only source-hash bypass was used.
    """

    train: Mapping[str, Any]
    holdout: Mapping[str, Any]
    manifest_dir: Path
    verification_receipt: Optional[Mapping[str, Any]]


def _require_mapping(value: Any, name: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ValueError(f"Catalog field {name!r} must be an object")
    return value


def _require_string(value: Any, name: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"Catalog field {name!r} must be a non-empty string")
    return value


def _require_int(value: Any, name: str, *, minimum: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
        raise ValueError(f"Catalog field {name!r} must be an integer >= {minimum}")
    return value


def _reject_unknown_fields(value: Mapping[str, Any], allowed: frozenset[str], name: str) -> None:
    unknown = sorted(set(value) - allowed)
    missing = sorted(allowed - set(value))
    if unknown:
        raise ValueError(f"Catalog {name} has unknown fields: {unknown}")
    if missing:
        raise ValueError(f"Catalog {name} is missing required fields: {missing}")


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as file_handle:
            while chunk := file_handle.read(8 * 1024 * 1024):
                digest.update(chunk)
    except OSError as error:
        raise ValueError(f"Could not read source token file {path}: {error}") from error
    return digest.hexdigest()


def _validate_loaded_builder_implementation() -> None:
    """Fail if the reviewed script bytes changed after this module was loaded."""
    current_sha256 = hashlib.sha256(Path(__file__).resolve().read_bytes()).hexdigest()
    if current_sha256 != BUILDER_IMPLEMENTATION_SHA256:
        raise ValueError(
            "Replay builder implementation changed after module load; restart from a stable "
            "reviewed checkout before emitting evidence"
        )


def _strict_json_object(pairs: Sequence[Tuple[str, Any]]) -> Dict[str, Any]:
    result: Dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"Replay input JSON repeats object key {key!r}")
        result[key] = value
    return result


@dataclass(frozen=True)
class _PinnedParentSource:
    source_id: str
    source_name: str
    parent_path_index: int
    parent_path: str
    num_tokens: int
    sha256: str


def _read_pinned_bytes(path: Path, expected_sha256: str, name: str) -> bytes:
    if _SHA256_RE.fullmatch(expected_sha256) is None:
        raise ValueError(f"Pinned {name} SHA-256 must be a lowercase SHA-256")
    try:
        raw = path.read_bytes()
    except OSError as error:
        raise ValueError(f"Could not read pinned {name} {path}: {error}") from error
    actual_sha256 = hashlib.sha256(raw).hexdigest()
    if actual_sha256 != expected_sha256:
        raise ValueError(f"Pinned {name} has SHA-256 {actual_sha256}, expected {expected_sha256}")
    return raw


def _load_parent_identity() -> Tuple[Path, str, Path, str, Tuple[Tuple[str, str], ...]]:
    parent_paths_file = Path(S002_PARENT_PATHS_FILE).expanduser().resolve()
    parent_paths_raw = _read_pinned_bytes(
        parent_paths_file,
        S002_PARENT_PATHS_SHA256,
        "s002 expanded path manifest",
    )
    try:
        parent_paths = parent_paths_raw.decode("utf-8").splitlines()
    except UnicodeDecodeError as error:
        raise ValueError("Pinned s002 expanded path manifest must be UTF-8") from error
    if not parent_paths or any(not path or path.strip() != path for path in parent_paths):
        raise ValueError("Pinned s002 path manifest must contain non-empty canonical paths")
    if len(set(parent_paths)) != len(parent_paths):
        raise ValueError("Pinned s002 path manifest repeats a path")

    parent_mix_file = Path(S002_PARENT_MIX_FILE).expanduser().resolve()
    parent_mix_raw = _read_pinned_bytes(
        parent_mix_file,
        S002_PARENT_MIX_SHA256,
        "OLMo-mix-0925 manifest",
    )
    try:
        mix_lines = parent_mix_raw.decode("utf-8").splitlines()
    except UnicodeDecodeError as error:
        raise ValueError("Pinned OLMo-mix-0925 manifest must be UTF-8") from error
    if len(mix_lines) != len(parent_paths):
        raise ValueError(
            "Pinned OLMo-mix-0925 and expanded path manifests differ in length: "
            f"{len(mix_lines)} versus {len(parent_paths)}"
        )

    parent_identity = []
    for index, (line, parent_path) in enumerate(zip(mix_lines, parent_paths)):
        source_name, separator, relative_path = line.partition(",")
        if (
            not separator
            or not source_name
            or not relative_path
            or "," in relative_path
            or source_name.strip() != source_name
            or relative_path.strip() != relative_path
        ):
            raise ValueError(f"Pinned OLMo-mix-0925 row {index} is not canonical LABEL,PATH")
        if "://" in relative_path or relative_path.startswith("/"):
            raise ValueError(f"Pinned OLMo-mix-0925 row {index} must contain a relative path")
        expanded_path = "s3://ai2-llm/" + relative_path.replace(
            "{TOKENIZER}", str(S002_TOKENIZER["identifier"])
        )
        if expanded_path != parent_path:
            raise ValueError(
                f"Pinned OLMo-mix-0925 row {index} expands to {expanded_path!r}, "
                f"not the checkpoint path {parent_path!r}"
            )
        parent_identity.append((source_name, parent_path))
    return (
        parent_paths_file,
        S002_PARENT_PATHS_SHA256,
        parent_mix_file,
        S002_PARENT_MIX_SHA256,
        tuple(parent_identity),
    )


def _load_upstream_provenance(
    parent_identity: Sequence[Tuple[str, str]],
    *,
    parent_paths_sha256: str,
    parent_mix_sha256: str,
) -> Tuple[Path, str, Tuple[_PinnedParentSource, ...]]:
    if S002_UPSTREAM_PROVENANCE_FILE is None or S002_UPSTREAM_PROVENANCE_SHA256 is None:
        raise ValueError(
            "Production native replay is closed: no independently reviewed upstream byte "
            "provenance is pinned. Data owners must publish the per-parent-path uint32 token "
            "count and full-file SHA-256, then set S002_UPSTREAM_PROVENANCE_FILE and "
            "S002_UPSTREAM_PROVENANCE_SHA256 in this builder."
        )
    provenance_file = Path(S002_UPSTREAM_PROVENANCE_FILE).expanduser().resolve()
    raw = _read_pinned_bytes(
        provenance_file,
        S002_UPSTREAM_PROVENANCE_SHA256,
        "s002 upstream byte provenance",
    )
    try:
        root = _require_mapping(
            json.loads(raw, object_pairs_hook=_strict_json_object),
            "upstream_provenance",
        )
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(
            f"Invalid upstream provenance JSON in {provenance_file}: {error}"
        ) from error
    _reject_unknown_fields(root, _UPSTREAM_ROOT_FIELDS, "upstream provenance root")
    if root["format"] != UPSTREAM_PROVENANCE_FORMAT:
        raise ValueError(f"Upstream provenance format must be {UPSTREAM_PROVENANCE_FORMAT!r}")
    version = _require_int(root["version"], "upstream_provenance.version", minimum=1)
    if version != UPSTREAM_PROVENANCE_VERSION:
        raise ValueError(
            f"Unsupported upstream provenance version {version}; "
            f"expected {UPSTREAM_PROVENANCE_VERSION}"
        )
    if root["hash_algorithm"] != "sha256":
        raise ValueError("Upstream provenance hash_algorithm must be 'sha256'")
    if root["parent_paths_sha256"] != parent_paths_sha256:
        raise ValueError("Upstream provenance does not bind the pinned s002 path manifest")
    if root["parent_mix_sha256"] != parent_mix_sha256:
        raise ValueError("Upstream provenance does not bind the pinned OLMo-mix-0925 manifest")

    raw_sources = root["sources"]
    if not isinstance(raw_sources, list) or len(raw_sources) != len(parent_identity):
        raise ValueError(
            "Upstream provenance must describe every pinned parent path exactly once: "
            f"expected {len(parent_identity)} entries"
        )
    sources_by_index: Dict[int, _PinnedParentSource] = {}
    for record_index, raw_source in enumerate(raw_sources):
        prefix = f"upstream_provenance.sources[{record_index}]"
        source = _require_mapping(raw_source, prefix)
        _reject_unknown_fields(source, _UPSTREAM_SOURCE_FIELDS, prefix)
        parent_path_index = _require_int(
            source["parent_path_index"], f"{prefix}.parent_path_index", minimum=0
        )
        if parent_path_index >= len(parent_identity):
            raise ValueError(f"{prefix}.parent_path_index is out of bounds")
        if parent_path_index in sources_by_index:
            raise ValueError(f"Upstream provenance repeats parent path index {parent_path_index}")
        source_name, expected_parent_path = parent_identity[parent_path_index]
        parent_path = _require_string(source["parent_path"], f"{prefix}.parent_path")
        if parent_path != expected_parent_path:
            raise ValueError(
                f"Upstream provenance parent path {parent_path_index} does not match the "
                "pinned checkpoint manifest"
            )
        num_tokens = _require_int(source["num_tokens"], f"{prefix}.num_tokens", minimum=1)
        source_sha256 = _require_string(source["sha256"], f"{prefix}.sha256")
        if _SHA256_RE.fullmatch(source_sha256) is None:
            raise ValueError(f"{prefix}.sha256 must be a lowercase SHA-256")
        path_digest = hashlib.sha256(parent_path.encode("utf-8")).hexdigest()
        source_id = f"s002-{parent_path_index:06d}-{path_digest[:16]}"
        sources_by_index[parent_path_index] = _PinnedParentSource(
            source_id=source_id,
            source_name=source_name,
            parent_path_index=parent_path_index,
            parent_path=parent_path,
            num_tokens=num_tokens,
            sha256=source_sha256,
        )
    if set(sources_by_index) != set(range(len(parent_identity))):
        raise ValueError("Upstream provenance does not cover every pinned parent path")
    return (
        provenance_file,
        S002_UPSTREAM_PROVENANCE_SHA256,
        tuple(sources_by_index[index] for index in range(len(parent_identity))),
    )


def load_source_catalog(
    path: os.PathLike[str] | str,
    *,
    verify_source_hashes: bool = True,
) -> SourceCatalog:
    """Load and strictly validate an s002 replay source catalog.

    The catalog is only a parent-index-to-local-path mapping. All semantic identity and byte
    metadata come from the pinned parent manifests and code-pinned upstream provenance. File
    existence and exact raw ``uint32`` size are always checked. SHA-256 verification is enabled
    by default; disabling it prevents this process from emitting a production receipt.

    :param path: Local JSON catalog path.
    :param verify_source_hashes: Stream every token file and compare its authoritative digest.
    :returns: The validated, deterministically ordered source catalog.
    :raises ValueError: If pinned lineage, JSON, paths, sizes, or hash checks are invalid.
    """
    (
        parent_paths_file,
        parent_paths_sha256,
        parent_mix_file,
        parent_mix_sha256,
        parent_identity,
    ) = _load_parent_identity()
    (
        upstream_provenance_file,
        upstream_provenance_sha256,
        pinned_sources,
    ) = _load_upstream_provenance(
        parent_identity,
        parent_paths_sha256=parent_paths_sha256,
        parent_mix_sha256=parent_mix_sha256,
    )

    catalog_path = Path(path).expanduser().resolve()
    try:
        raw = catalog_path.read_bytes()
    except OSError as error:
        raise ValueError(f"Could not read source catalog {catalog_path}: {error}") from error
    try:
        root = _require_mapping(json.loads(raw, object_pairs_hook=_strict_json_object), "root")
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(f"Invalid source catalog JSON in {catalog_path}: {error}") from error

    _reject_unknown_fields(root, _ROOT_FIELDS, "root")
    if root["format"] != SOURCE_CATALOG_FORMAT:
        raise ValueError(f"Catalog format must be {SOURCE_CATALOG_FORMAT!r}")
    version = _require_int(root["version"], "version", minimum=1)
    if version != SOURCE_CATALOG_VERSION:
        raise ValueError(
            f"Unsupported source catalog version {version}; expected {SOURCE_CATALOG_VERSION}"
        )

    raw_sources = root["sources"]
    if not isinstance(raw_sources, list) or not raw_sources:
        raise ValueError("Catalog field 'sources' must be a non-empty list")

    parent_path_indices = set()
    resolved_paths = set()
    sources = []
    for index, raw_source in enumerate(raw_sources):
        prefix = f"sources[{index}]"
        source = _require_mapping(raw_source, prefix)
        _reject_unknown_fields(source, _SOURCE_FIELDS, prefix)
        parent_path_index = _require_int(
            source["parent_path_index"], f"{prefix}.parent_path_index", minimum=0
        )
        if parent_path_index >= len(pinned_sources):
            raise ValueError(f"Catalog parent_path_index {parent_path_index} is out of bounds")
        if parent_path_index in parent_path_indices:
            raise ValueError(f"Catalog repeats parent_path_index {parent_path_index}")
        parent_path_indices.add(parent_path_index)
        pinned_source = pinned_sources[parent_path_index]
        token_path = _require_string(source["path"], f"{prefix}.path")
        if "://" in token_path:
            raise ValueError(
                f"Catalog parent path {parent_path_index} must be materialized locally, "
                f"got {token_path!r}"
            )
        unresolved_path = Path(token_path).expanduser()
        resolved_path = (
            unresolved_path if unresolved_path.is_absolute() else catalog_path.parent / token_path
        ).resolve()
        if resolved_path in resolved_paths:
            raise ValueError(f"Catalog token path is listed more than once: {resolved_path}")
        resolved_paths.add(resolved_path)

        try:
            actual_size = resolved_path.stat().st_size
        except OSError as error:
            raise ValueError(
                f"Could not stat source token file {resolved_path}: {error}"
            ) from error
        expected_size = pinned_source.num_tokens * TOKEN_ITEM_SIZE
        if actual_size != expected_size:
            raise ValueError(
                f"Materialized parent source {pinned_source.source_id!r} has {actual_size} "
                f"bytes, expected {expected_size} for {pinned_source.num_tokens} "
                f"authoritative {TOKEN_DTYPE} tokens"
            )
        if verify_source_hashes:
            actual_hash = _sha256_file(resolved_path)
            if actual_hash != pinned_source.sha256:
                raise ValueError(
                    f"Materialized parent source {pinned_source.source_id!r} has SHA-256 "
                    f"{actual_hash}, expected authoritative {pinned_source.sha256}"
                )

        sources.append(
            CatalogSource(
                source_id=pinned_source.source_id,
                source_name=pinned_source.source_name,
                parent_path_index=parent_path_index,
                parent_path=pinned_source.parent_path,
                catalog_path=token_path,
                resolved_path=resolved_path,
                num_tokens=pinned_source.num_tokens,
                sha256=pinned_source.sha256,
            )
        )

    if parent_path_indices != set(range(len(pinned_sources))):
        raise ValueError(
            "Replay source catalog must materialize every pinned parent path exactly once: "
            f"expected {len(pinned_sources)}, got {len(parent_path_indices)}"
        )
    ordered_sources = tuple(sorted(sources, key=lambda item: item.source_id))
    semantic_paths = [
        {
            "id": source.source_id,
            "source": source.source_name,
            "parent_path_index": source.parent_path_index,
            "parent_path": source.parent_path,
            "path": str(source.resolved_path),
            "num_tokens": source.num_tokens,
            "sha256": source.sha256,
        }
        for source in ordered_sources
    ]
    canonical_paths = json.dumps(
        {
            "parent_paths_sha256": parent_paths_sha256,
            "parent_mix_sha256": parent_mix_sha256,
            "upstream_provenance_sha256": upstream_provenance_sha256,
            "sources": semantic_paths,
        },
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return SourceCatalog(
        path=catalog_path,
        sources=ordered_sources,
        catalog_sha256=hashlib.sha256(raw).hexdigest(),
        parent_paths_sha256=parent_paths_sha256,
        parent_paths_file=parent_paths_file,
        parent_mix_sha256=parent_mix_sha256,
        parent_mix_file=parent_mix_file,
        upstream_provenance_sha256=upstream_provenance_sha256,
        upstream_provenance_file=upstream_provenance_file,
        materialized_sources_sha256=hashlib.sha256(canonical_paths).hexdigest(),
        source_hashes_verified=verify_source_hashes,
    )


def _validate_budget(name: str, tokens: int, loss_tokens_per_window: int) -> int:
    if isinstance(tokens, bool) or not isinstance(tokens, int) or tokens <= 0:
        raise ValueError(f"{name} must be a positive integer")
    if tokens % loss_tokens_per_window:
        raise ValueError(
            f"{name}={tokens} is not divisible by loss_tokens_per_window="
            f"{loss_tokens_per_window}; "
            "usable token budgets are never rounded"
        )
    return tokens // loss_tokens_per_window


def _quota_windows(
    quotas: Optional[Mapping[str, int]],
    *,
    name: str,
    loss_tokens_per_window: int,
    source_names: frozenset[str],
) -> Dict[str, int]:
    result = {source_name: 0 for source_name in source_names}
    for source_name, tokens in (quotas or {}).items():
        if source_name not in source_names:
            raise ValueError(f"{name} names unknown source label {source_name!r}")
        if isinstance(tokens, bool) or not isinstance(tokens, int) or tokens < 0:
            raise ValueError(f"{name}[{source_name!r}] must be a non-negative integer")
        if tokens % loss_tokens_per_window:
            raise ValueError(
                f"{name}[{source_name!r}]={tokens} is not divisible by "
                f"loss_tokens_per_window={loss_tokens_per_window}"
            )
        result[source_name] = tokens // loss_tokens_per_window
    return result


def _apportion_exact(
    total: int,
    capacities: Mapping[str, int],
    minima: Optional[Mapping[str, int]] = None,
) -> Dict[str, int]:
    keys = sorted(capacities)
    if not keys:
        raise ValueError("Cannot apportion over an empty source set")
    allocations = {key: int((minima or {}).get(key, 0)) for key in keys}
    for key in keys:
        capacity = capacities[key]
        minimum = allocations[key]
        if capacity < 0 or minimum < 0:
            raise ValueError("Allocation capacities and minima must be non-negative")
        if minimum > capacity:
            raise ValueError(
                f"Minimum quota for {key!r} is {minimum} windows, above capacity {capacity}"
            )
    minimum_total = sum(allocations.values())
    capacity_total = sum(capacities.values())
    if minimum_total > total:
        raise ValueError(
            f"Minimum quotas require {minimum_total} windows, above requested total {total}"
        )
    if total > capacity_total:
        raise ValueError(
            f"Requested {total} windows, but materialized sources hold only "
            f"{capacity_total} disjoint windows"
        )

    remaining = total - minimum_total
    residual = {key: capacities[key] - allocations[key] for key in keys}
    residual_total = sum(residual.values())
    if remaining == 0:
        return allocations
    if residual_total < remaining:
        raise ValueError("Minimum quotas leave insufficient capacity for requested total")

    remainders = []
    assigned = 0
    for key in keys:
        numerator = remaining * residual[key]
        quotient, remainder = divmod(numerator, residual_total)
        allocations[key] += quotient
        assigned += quotient
        remainders.append((remainder, key))
    for _, key in sorted(remainders, key=lambda item: (-item[0], item[1])):
        if assigned == remaining:
            break
        if allocations[key] < capacities[key]:
            allocations[key] += 1
            assigned += 1
    if assigned != remaining:
        raise AssertionError("Exact apportionment failed to assign its integer remainder")
    return allocations


def _permutation_prefix(capacity: int, count: int, *, seed: int, source_id: str) -> Tuple[int, ...]:
    if count < 0 or count > capacity:
        raise ValueError(f"Cannot select {count} unique slots from capacity {capacity}")
    if count == 0:
        return ()
    if capacity == 1:
        return (0,)
    selection_key = json.dumps(
        [SELECTION_ALGORITHM, seed, source_id],
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    digest = hashlib.sha256(selection_key).digest()
    multiplier = int.from_bytes(digest[:16], "big") % capacity
    offset = int.from_bytes(digest[16:], "big") % capacity
    if multiplier == 0:
        multiplier = 1
    while math.gcd(multiplier, capacity) != 1:
        multiplier = (multiplier + 1) % capacity
        if multiplier == 0:
            multiplier = 1
    return tuple((multiplier * index + offset) % capacity for index in range(count))


def _manifest_token_path(source: CatalogSource, manifest_dir: Path) -> str:
    return Path(os.path.relpath(source.resolved_path, start=manifest_dir)).as_posix()


def _serialized_json_bytes(value: Mapping[str, Any]) -> bytes:
    return (json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def _build_verification_receipt(catalog: SourceCatalog) -> Optional[Dict[str, Any]]:
    if not catalog.source_hashes_verified:
        return None
    return {
        "format": VERIFICATION_RECEIPT_FORMAT,
        "version": VERIFICATION_RECEIPT_VERSION,
        "hash_algorithm": "sha256",
        "builder_implementation": BUILDER_IMPLEMENTATION_REFERENCE,
        "builder_sha256": BUILDER_IMPLEMENTATION_SHA256,
        "source_catalog_sha256": catalog.catalog_sha256,
        "parent_paths_sha256": catalog.parent_paths_sha256,
        "parent_mix_sha256": catalog.parent_mix_sha256,
        "upstream_provenance_sha256": catalog.upstream_provenance_sha256,
        "materialized_sources_sha256": catalog.materialized_sources_sha256,
        "sources": [
            {
                "id": source.source_id,
                "source": source.source_name,
                "parent_path_index": source.parent_path_index,
                "parent_path": source.parent_path,
                "resolved_path": str(source.resolved_path),
                "num_tokens": source.num_tokens,
                "size_bytes": source.size_bytes,
                "sha256": source.sha256,
            }
            for source in catalog.sources
        ],
    }


def _make_manifest(
    *,
    split: str,
    selected_starts: Mapping[str, Tuple[int, ...]],
    catalog: SourceCatalog,
    manifest_dir: Path,
    sequence_length: int,
    seed: int,
    minimum_source_windows: Mapping[str, int],
    verification_receipt_sha256: Optional[str],
) -> Dict[str, Any]:
    loss_tokens_per_window = sequence_length - 1
    sources: list[Dict[str, Any]] = []
    for source in catalog.sources:
        starts = selected_starts.get(source.source_id, ())
        if not starts:
            continue
        sources.append(
            {
                "id": source.source_id,
                "source": source.source_name,
                "parent_path_index": source.parent_path_index,
                "parent_path": source.parent_path,
                "path": _manifest_token_path(source, manifest_dir),
                "num_tokens": source.num_tokens,
                "size_bytes": source.size_bytes,
                "sha256": source.sha256,
                "window_starts": list(starts),
            }
        )
    num_windows = sum(len(source["window_starts"]) for source in sources)
    source_usable_tokens: Dict[str, int] = {}
    for source_record in sources:
        source_name = source_record["source"]
        source_usable_tokens[source_name] = source_usable_tokens.get(source_name, 0) + (
            len(source_record["window_starts"]) * loss_tokens_per_window
        )
    provenance: Dict[str, Any] = {
        "parent_checkpoint": S002_PARENT_CHECKPOINT,
        "parent_mix": S002_PARENT_MIX,
        "parent_paths_sha256": catalog.parent_paths_sha256,
        "parent_mix_sha256": catalog.parent_mix_sha256,
        "upstream_provenance_sha256": catalog.upstream_provenance_sha256,
        "builder_implementation": BUILDER_IMPLEMENTATION_REFERENCE,
        "builder_sha256": BUILDER_IMPLEMENTATION_SHA256,
        "instance_filter": dict(S002_INSTANCE_FILTER),
        "materialized_sources_sha256": catalog.materialized_sources_sha256,
        "source_catalog_sha256": catalog.catalog_sha256,
        "source_catalog_format": SOURCE_CATALOG_FORMAT,
        "source_catalog_version": SOURCE_CATALOG_VERSION,
        "selection_algorithm": SELECTION_ALGORITHM,
        "selection_seed": seed,
        "split": split,
        "usable_tokens": num_windows * loss_tokens_per_window,
        "source_usable_tokens": source_usable_tokens,
        "minimum_source_usable_tokens": {
            source_name: windows * loss_tokens_per_window
            for source_name, windows in sorted(minimum_source_windows.items())
            if windows
        },
        "raw_tokens_per_window": sequence_length,
        "loss_tokens_per_window": loss_tokens_per_window,
    }
    if verification_receipt_sha256 is not None:
        provenance["verification_receipt_sha256"] = verification_receipt_sha256
    return {
        "format": NATIVE_TEXT_REPLAY_FORMAT,
        "version": NATIVE_TEXT_REPLAY_VERSION,
        "sequence_length": sequence_length,
        "dtype": TOKEN_DTYPE,
        "tokenizer": dict(S002_TOKENIZER),
        "provenance": provenance,
        "num_windows": num_windows,
        "sources": sources,
    }


def build_replay_manifests(
    catalog: SourceCatalog,
    *,
    manifest_dir: os.PathLike[str] | str,
    sequence_length: int,
    train_usable_tokens: int,
    holdout_usable_tokens: int,
    seed: int = 6198,
    train_minimum_source_tokens: Optional[Mapping[str, int]] = None,
    holdout_minimum_source_tokens: Optional[Mapping[str, int]] = None,
) -> ReplayManifestPair:
    """Select deterministic, disjoint train and holdout replay windows.

    The union is apportioned across source labels by usable capacity after reserving both
    splits' rare-source minima. Holdout is then apportioned within that union while reserving
    the train minima. File-level allocation follows the same exact integer method. Each file
    uses a seeded affine permutation of the fixed ``sequence_length`` parent FSL grid, which
    selects unique slots without enumerating the full corpus.

    :param catalog: Validated local source catalog.
    :param manifest_dir: Directory against which output token paths will be relative.
    :param sequence_length: Number of loss-bearing tokens in each dataset example.
    :param train_usable_tokens: Exact train budget, divisible by ``sequence_length``.
    :param holdout_usable_tokens: Exact holdout budget, divisible by ``sequence_length``.
    :param seed: Non-negative deterministic selection seed.
    :param train_minimum_source_tokens: Minimum train usable tokens by source label.
    :param holdout_minimum_source_tokens: Minimum holdout usable tokens by source label.
    :returns: In-memory train and holdout manifests with no overlapping raw intervals.
    :raises ValueError: If budgets, quotas, sources, or capacities are inconsistent.
    """
    _validate_loaded_builder_implementation()
    if isinstance(sequence_length, bool) or not isinstance(sequence_length, int):
        raise ValueError("sequence_length must be a positive integer")
    if sequence_length < 2:
        raise ValueError("sequence_length must be an integer >= 2")
    if isinstance(seed, bool) or not isinstance(seed, int) or seed < 0:
        raise ValueError("seed must be a non-negative integer")
    loss_tokens_per_window = sequence_length - 1
    train_windows = _validate_budget(
        "train_usable_tokens", train_usable_tokens, loss_tokens_per_window
    )
    holdout_windows = _validate_budget(
        "holdout_usable_tokens", holdout_usable_tokens, loss_tokens_per_window
    )
    raw_window_length = sequence_length
    file_capacities = {
        source.source_id: source.num_tokens // raw_window_length for source in catalog.sources
    }
    unusable = [source_id for source_id, capacity in file_capacities.items() if capacity == 0]
    if unusable:
        raise ValueError(
            f"Catalog sources {unusable} are shorter than one {raw_window_length}-token window"
        )

    source_names = frozenset(source.source_name for source in catalog.sources)
    train_minima = _quota_windows(
        train_minimum_source_tokens,
        name="train_minimum_source_tokens",
        loss_tokens_per_window=loss_tokens_per_window,
        source_names=source_names,
    )
    holdout_minima = _quota_windows(
        holdout_minimum_source_tokens,
        name="holdout_minimum_source_tokens",
        loss_tokens_per_window=loss_tokens_per_window,
        source_names=source_names,
    )
    label_capacities = {
        source_name: sum(
            file_capacities[source.source_id]
            for source in catalog.sources
            if source.source_name == source_name
        )
        for source_name in source_names
    }
    union_minima = {
        source_name: train_minima[source_name] + holdout_minima[source_name]
        for source_name in source_names
    }
    union_by_label = _apportion_exact(
        train_windows + holdout_windows,
        label_capacities,
        union_minima,
    )
    holdout_capacities = {
        source_name: union_by_label[source_name] - train_minima[source_name]
        for source_name in source_names
    }
    holdout_by_label = _apportion_exact(
        holdout_windows,
        holdout_capacities,
        holdout_minima,
    )

    train_starts: Dict[str, Tuple[int, ...]] = {}
    holdout_starts: Dict[str, Tuple[int, ...]] = {}
    for source_name in sorted(source_names):
        sources = [source for source in catalog.sources if source.source_name == source_name]
        capacities = {source.source_id: file_capacities[source.source_id] for source in sources}
        union_by_file = _apportion_exact(union_by_label[source_name], capacities)
        holdout_by_file = _apportion_exact(
            holdout_by_label[source_name],
            union_by_file,
        )
        for source in sources:
            selected_slots = _permutation_prefix(
                file_capacities[source.source_id],
                union_by_file[source.source_id],
                seed=seed,
                source_id=source.source_id,
            )
            holdout_count = holdout_by_file[source.source_id]
            holdout_starts[source.source_id] = tuple(
                sorted(slot * raw_window_length for slot in selected_slots[:holdout_count])
            )
            train_starts[source.source_id] = tuple(
                sorted(slot * raw_window_length for slot in selected_slots[holdout_count:])
            )

    resolved_manifest_dir = Path(manifest_dir).expanduser().resolve()
    verification_receipt = _build_verification_receipt(catalog)
    verification_receipt_sha256 = (
        hashlib.sha256(_serialized_json_bytes(verification_receipt)).hexdigest()
        if verification_receipt is not None
        else None
    )
    train_manifest = _make_manifest(
        split="train",
        selected_starts=train_starts,
        catalog=catalog,
        manifest_dir=resolved_manifest_dir,
        sequence_length=sequence_length,
        seed=seed,
        minimum_source_windows=train_minima,
        verification_receipt_sha256=verification_receipt_sha256,
    )
    holdout_manifest = _make_manifest(
        split="holdout",
        selected_starts=holdout_starts,
        catalog=catalog,
        manifest_dir=resolved_manifest_dir,
        sequence_length=sequence_length,
        seed=seed,
        minimum_source_windows=holdout_minima,
        verification_receipt_sha256=verification_receipt_sha256,
    )
    if train_manifest["num_windows"] != train_windows:
        raise AssertionError("Train selection did not meet its exact window budget")
    if holdout_manifest["num_windows"] != holdout_windows:
        raise AssertionError("Holdout selection did not meet its exact window budget")
    return ReplayManifestPair(
        train=train_manifest,
        holdout=holdout_manifest,
        manifest_dir=resolved_manifest_dir,
        verification_receipt=verification_receipt,
    )


def _write_json_temp(path: Path, value: Mapping[str, Any]) -> Path:
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as file_handle:
        file_handle.write(_serialized_json_bytes(value).decode("utf-8"))
        return Path(file_handle.name)


def write_replay_manifests(
    manifests: ReplayManifestPair,
    *,
    train_path: os.PathLike[str] | str,
    holdout_path: os.PathLike[str] | str,
    overwrite: bool = False,
) -> Tuple[NativeTextReplayManifest, NativeTextReplayManifest]:
    """Schema-validate and atomically write each file in a replay manifest pair.

    Both output paths must share a directory because token paths were made relative to the
    single ``manifest_dir`` passed to :func:`build_replay_manifests`. When the source files
    were fully hash-verified, the same directory also receives a pinned integrity receipt.

    :param manifests: In-memory manifest pair to write.
    :param train_path: Train JSON output path.
    :param holdout_path: Holdout JSON output path.
    :param overwrite: Replace existing manifest files when true.
    :returns: The two validated native manifest objects.
    :raises ValueError: If paths collide or use different directories.
    :raises FileExistsError: If an output exists and overwrite is false.
    """
    # Keep catalog validation and ``--dry-run`` lightweight. The native loader pulls in the
    # multimodal stack, so import it only when schema-validating files that were actually written.
    from olmo_core.data.multimodal.native_text_replay import (
        NativeTextReplayManifest,
        NativeTextReplayVerificationReceipt,
    )

    resolved_train = Path(train_path).expanduser().resolve()
    resolved_holdout = Path(holdout_path).expanduser().resolve()
    resolved_receipt = manifests.manifest_dir / VERIFICATION_RECEIPT_FILENAME
    if resolved_train == resolved_holdout:
        raise ValueError("Train and holdout manifest paths must be distinct")
    if manifests.verification_receipt is not None and resolved_receipt in {
        resolved_train,
        resolved_holdout,
    }:
        raise ValueError(
            "Train and holdout manifest paths must be distinct from the verification receipt"
        )
    if resolved_train.parent != resolved_holdout.parent:
        raise ValueError("Train and holdout manifests must be written to the same directory")
    if resolved_train.parent != manifests.manifest_dir:
        raise ValueError(
            f"Manifest pair was built for directory {manifests.manifest_dir}, "
            f"not {resolved_train.parent}"
        )
    output_paths = [resolved_train, resolved_holdout]
    if manifests.verification_receipt is not None:
        output_paths.append(resolved_receipt)
    existing = [path for path in output_paths if path.exists()]
    if existing and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing manifests: {existing}")

    resolved_train.parent.mkdir(parents=True, exist_ok=True)
    temp_paths = []
    try:
        train_temp = _write_json_temp(resolved_train, manifests.train)
        temp_paths.append(train_temp)
        holdout_temp = _write_json_temp(resolved_holdout, manifests.holdout)
        temp_paths.append(holdout_temp)
        receipt_temp = None
        if manifests.verification_receipt is not None:
            receipt_temp = _write_json_temp(resolved_receipt, manifests.verification_receipt)
            temp_paths.append(receipt_temp)
        NativeTextReplayManifest.load(train_temp)
        NativeTextReplayManifest.load(holdout_temp)
        if receipt_temp is not None:
            expected_receipt_sha256 = manifests.train["provenance"]["verification_receipt_sha256"]
            receipt = NativeTextReplayVerificationReceipt.load(
                receipt_temp,
                expected_sha256=expected_receipt_sha256,
            )
            receipt.validate_manifest(NativeTextReplayManifest.load(train_temp))
            receipt.validate_manifest(NativeTextReplayManifest.load(holdout_temp))
            os.replace(receipt_temp, resolved_receipt)
            temp_paths.remove(receipt_temp)
        os.replace(train_temp, resolved_train)
        temp_paths.remove(train_temp)
        os.replace(holdout_temp, resolved_holdout)
        temp_paths.remove(holdout_temp)
    finally:
        for temp_path in temp_paths:
            temp_path.unlink(missing_ok=True)

    return (
        NativeTextReplayManifest.load(resolved_train),
        NativeTextReplayManifest.load(resolved_holdout),
    )


def _parse_minimum_source_tokens(values: Sequence[str], option_name: str) -> Dict[str, int]:
    quotas: Dict[str, int] = {}
    for value in values:
        source_name, separator, raw_tokens = value.partition("=")
        if not separator or not source_name or not raw_tokens:
            raise ValueError(f"{option_name} values must have the form SOURCE=TOKENS")
        if source_name in quotas:
            raise ValueError(f"{option_name} repeats source label {source_name!r}")
        try:
            tokens = int(raw_tokens)
        except ValueError as error:
            raise ValueError(f"{option_name} token count must be an integer: {value!r}") from error
        if tokens < 0:
            raise ValueError(f"{option_name} token count must be non-negative: {value!r}")
        quotas[source_name] = tokens
    return quotas


def _build_parser() -> argparse.ArgumentParser:
    example = r"""Example:
  python src/scripts/data/build_s002_replay_manifest.py \
    --catalog /data/s002-replay-sources.json \
    --output-dir /data/vision-alignment/replay \
    --sequence-length 8192 --train-tokens 819100000 \
    --holdout-tokens 8191000 \
    --train-min-source-tokens wikipedia=8191000

Budgets and quotas count loss-bearing tokens and must be exact multiples of
--sequence-length minus one. Source files are never modified."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=example,
    )
    parser.add_argument(
        "--catalog",
        type=Path,
        required=True,
        help="Strict parent-index-to-local-path materialization catalog JSON.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory for native-text-replay-train.json and -holdout.json.",
    )
    parser.add_argument(
        "--sequence-length",
        type=int,
        default=8192,
        help="Raw tokens per parent FSL example; nominal loss tokens are L-1 (default: 8192).",
    )
    parser.add_argument(
        "--train-tokens",
        type=int,
        required=True,
        help="Exact loss-bearing token budget for the finite train split.",
    )
    parser.add_argument(
        "--holdout-tokens",
        type=int,
        required=True,
        help="Exact loss-bearing token budget for the disjoint holdout split.",
    )
    parser.add_argument(
        "--train-min-source-tokens",
        metavar="SOURCE=TOKENS",
        action="append",
        default=[],
        help="Repeatable exact minimum train quota for a rare source label.",
    )
    parser.add_argument(
        "--holdout-min-source-tokens",
        metavar="SOURCE=TOKENS",
        action="append",
        default=[],
        help="Repeatable exact minimum holdout quota for a rare source label.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=6198,
        help="Deterministic window-selection seed (default: 6198).",
    )
    parser.add_argument(
        "--skip-source-hash-verification",
        action="store_true",
        help=(
            "Development only: skip comparing materialized files to authoritative SHA-256 "
            "values; this disables verification-receipt emission."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and print the exact allocation without writing manifests.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace existing train and holdout manifest JSON files.",
    )
    return parser


def _source_counts(manifest: Mapping[str, Any]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for source in manifest["sources"]:
        source_name = source["source"]
        counts[source_name] = counts.get(source_name, 0) + len(source["window_starts"])
    return counts


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Run the offline s002 replay-manifest builder CLI.

    :param argv: Optional argument vector for tests and programmatic use.
    :returns: Zero after a successful dry run or write.
    """
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        train_minima = _parse_minimum_source_tokens(
            args.train_min_source_tokens, "--train-min-source-tokens"
        )
        holdout_minima = _parse_minimum_source_tokens(
            args.holdout_min_source_tokens, "--holdout-min-source-tokens"
        )
        catalog = load_source_catalog(
            args.catalog,
            verify_source_hashes=not args.skip_source_hash_verification,
        )
        manifests = build_replay_manifests(
            catalog,
            manifest_dir=args.output_dir,
            sequence_length=args.sequence_length,
            train_usable_tokens=args.train_tokens,
            holdout_usable_tokens=args.holdout_tokens,
            seed=args.seed,
            train_minimum_source_tokens=train_minima,
            holdout_minimum_source_tokens=holdout_minima,
        )
        train_path = args.output_dir / "native-text-replay-train.json"
        holdout_path = args.output_dir / "native-text-replay-holdout.json"
        if not args.dry_run:
            write_replay_manifests(
                manifests,
                train_path=train_path,
                holdout_path=holdout_path,
                overwrite=args.overwrite,
            )
    except (FileExistsError, OSError, ValueError) as error:
        parser.error(str(error))

    summary = {
        "dry_run": args.dry_run,
        "catalog": str(catalog.path),
        "catalog_sha256": catalog.catalog_sha256,
        "parent_paths_sha256": catalog.parent_paths_sha256,
        "parent_mix_sha256": catalog.parent_mix_sha256,
        "builder": {
            "implementation": BUILDER_IMPLEMENTATION_REFERENCE,
            "sha256": BUILDER_IMPLEMENTATION_SHA256,
        },
        "upstream_provenance": {
            "path": str(catalog.upstream_provenance_file),
            "sha256": catalog.upstream_provenance_sha256,
        },
        "materialized_sources_sha256": catalog.materialized_sources_sha256,
        "source_hashes_verified": catalog.source_hashes_verified,
        "verification_receipt": (
            {
                "path": str(args.output_dir / VERIFICATION_RECEIPT_FILENAME),
                "sha256": manifests.train["provenance"]["verification_receipt_sha256"],
            }
            if manifests.verification_receipt is not None
            else None
        ),
        "sequence_length": args.sequence_length,
        "raw_tokens_per_window": args.sequence_length,
        "loss_tokens_per_window": args.sequence_length - 1,
        "train": {
            "path": str(train_path),
            "num_windows": manifests.train["num_windows"],
            "usable_tokens": manifests.train["provenance"]["usable_tokens"],
            "source_windows": _source_counts(manifests.train),
        },
        "holdout": {
            "path": str(holdout_path),
            "num_windows": manifests.holdout["num_windows"],
            "usable_tokens": manifests.holdout["provenance"]["usable_tokens"],
            "source_windows": _source_counts(manifests.holdout),
        },
    }
    print(json.dumps(summary, sort_keys=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
